FROM hafid11afridian/php-fpm:7.1.19

RUN curl https://getcomposer.org/download/1.6.5/composer.phar -o /usr/local/bin/composer.phar \
    && chmod a+x /usr/local/bin/composer.phar \
    && ln -s /usr/local/bin/composer.phar /usr/local/bin/composer

