FROM dockerkit/php-fpm:7.0.10

RUN curl https://getcomposer.org/download/1.2.0/composer.phar -o /usr/local/bin/composer.phar \
    && chmod a+x /usr/local/bin/composer.phar \
    && ln -s /usr/local/bin/composer.phar /usr/local/bin/composer

